### PR TITLE
Dashboard  fix a link nmea_converter

### PR DESCRIPTION
**Pull request by rgleason**

### CODE REVIEW

**Comment by rgleason** [comment]
Still an unrelated problem that needs to be fixed in admiralty_tide_tables_pi
I guess it has to be fixed?

```
+ antora site.yml
error: Local content source does not exist: /home/runner/work/plugins/plugins/sources/admiralty_tide_tables_pi (url: sources/admiralty_tide_tables_pi)
Add the --stacktrace option to see the cause.
Error: Process completed with exit code 1.
```

**Comment by rgleason** [comment]
The changes here were not mine. Don't know what happened. This is causing the problem..
https://github.com/opencpn-manuals/plugins/commit/04ce56d4e9f8733b0cde2d5dd12b73bc9e14f3b5

How do I get the other commits  committed to "Main"

**Comment by rgleason** [comment]
I would have to have a local branch "build" to work on this.
Can I remove this commit in some easy way?

**Comment by rgleason** [comment]
Maybe I now need to use
./source..state.sh save ?

**Comment by leamas** [comment]
opencpn-manuals/plugins is at a9fd5525 for me, and shows no such problems whatsoever.  Ergo: no files committed into git, including sources.state should be changed. Make sure you have a clean index.

Then, since you seems to have some serious problems with sources: Remove everything under sources (besides .gitkeep) and re-run ./source-state.sh restore.

**Comment by Rasbats** [comment]
With commit a358adc7c78906d21743311193d2261334ece827 I did restore/update/save and then did a local build.

Lots of fatals with the restore, which were ignored. Then update worked and then I saved the sources.state file. 

Pushed the updated sources.state to main.

**Comment by Rasbats** [comment]
Da.n: The list needs sorting again. I will do this.

**Comment by leamas** [comment]
@rasbats: which brings us back to #41. More there...

**Comment by rgleason** [comment]
I did that yesterday and got it all working all day and it was all working last night, what happened?
Am I going to loose my changes?

" Ergo: no files committed into git, including sources.state should be changed."  That is because I am being blocked by this ridiculous commit/change that I did not make!

Now have deleted all sources folders except gitkeep
Then did  ./source-state.sh restore  and then two ./source-state.sh update  and it looks clean again.

What would I do next?  I can't generate docs for the "build" branch so I can see the changes? - I don't have that locally...yet.

Or do I go back to 
https://github.com/opencpn-manuals/plugins/pull/44
https://github.com/opencpn-manuals/plugins/runs/3621731070  and try to merge again?

**Comment by rgleason** [comment]
Is this problem due to multiple people working on this at the same time?   
Maybe we need some kind of semaphore?

**Comment by leamas** [comment]
With all sources in place you should be able to make a local build: _ antora site.yml_. Creates the docs dir. There is no point with a local build branch. just use main.

You need to get used to the fact that you are not alone.  Mike, I and you all commits into this repo, and collisions are inevitable. However, something you have pushed is never lost, it's always available in the history.

No idea where you are right now. What is your HEAD commit?

**Comment by leamas** [comment]
Working together like this is one  the real strengths of git. However, you need to know your toolbox...

**Comment by rgleason** [comment]
`"With all sources in place you should be able to make a local build: _ antora site.yml_. Creates the docs dir. There is no point with a local build branch. just use main."  `
    Yes, I've been doing that a lot. But Not this morning.

`You need to get used to the fact that you are not alone. Mike, I and you all commits into this repo, and collisions are inevitable. However, something you have pushed is never lost, it's always available in the history.
`
Ok that's good.  The pushes are in the "build" branch  here  
See the changes/commits made  https://github.com/opencpn-manuals/plugins/pull/44
At the commit  Merge branch 'main' into build   [04ce56d](https://github.com/opencpn-manuals/plugins/commit/04ce56d4e9f8733b0cde2d5dd12b73bc9e14f3b5)   it turned bad as  I tried to merge in subsequent commits.
Merge https://github.com/opencpn-manuals/plugins/runs/3621731070
     I can't get them accepted into the main branch.

This morning I was working using the online "Edit" feature mostly.
However I was asked to create a clone of nmea_converter which I did and I made changes there too. 

Here is where my head is now
```
Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$ git branch -va
* main                       3bc4cee Update sources to latest versions
  remotes/origin/HEAD        -> origin/main
  remotes/origin/build       3bc4cee Update sources to latest versions
  remotes/origin/gh-pages    8a22c7b [full-linkcheck] [CI] Updating gh-pages branch from e73490f6
  remotes/origin/main        3bc4cee Update sources to latest versions
  remotes/origin/review-base 8c4e0fc Merge pull request #24 from leamas/main-review
  remotes/origin/site-paths  ad0a5ce site.yml: Adjust paths to match specifications
  remotes/origin/testing     ef726dc Testing chartscale edits.

Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
```

**Comment by rgleason** [comment]
I notice these commits are in a PR from opencpn-manuals/plugins  https://github.com/opencpn-manuals/plugins/pulls

**Comment by leamas** [comment]
Many things wrong here. First of them:  you should not make PRs and not make merges. Instead, use the workflow described in WORKFLOWS.adoc. They are based on that you rebase and commit directly, no need for a PR.

Now, you of course cannot push a commit that does not build locally.  We need a clear description of your situation:

  - What commit is your opencpn-manuals/plugins at, the one that works?
  - Where are are the changes you are trying to do? Exactly?

**Comment by rgleason** [comment]
Alec I was largely using the online "Edit" button for most of this.
What exactly is the process that we should follow for that?

1. "Edit Button" results in a PR to the "build" branch which is "Merged"
2.  Then you are presented with the result to view it and check it.
3.  Then I have tried to make a PR to the "main" branch using squash, but was stymied by this particular commit that appeared.
4.  When using the Edit button, I was prompted to "fork" a plugin (nmea_converter") whiich I did, and made changes from within that interface (not locally) and then commited them and made a PR to Dirk's repos.
5.  I then went on using the Edit Buttons to make additional changes and tried to PR to 'main" 
5. Perhaps you can advise precisely what you want?

I wonder if this is going to get confusing for users trying to make changes?

**Comment by leamas** [comment]
Please don't do that. It is fine for users which want's to update a plugin manual, but definitely not to changes in opencpn-manuals/plugins. And no casual drive-by user should change that.

We are now talking about opencpn-manuals/plugins. Same questions:


  -  What commit is your opencpn-manuals/plugins at, the one that works?
  -  Where are are the changes you are trying to do? Exactly?

**Comment by rgleason** [comment]
**Please don't do that. It is fine for users which want's to update a plugin manual, but definitely not to changes in opencpn-manuals/plugins. And no casual drive-by user should change that.**

OK - The Online "EDIT Button" is ONLY for updating a specific "distributed" plugin manual, NOT for use with opencpn-manuals/plugins!!    Maybe a note in Workflow?

```
We are now talking about opencpn-manuals/plugins. Same questions:

    What commit is your opencpn-manuals/plugins at, the one that works?
    Where are are the changes you are trying to do? Exactly?

```
Please see  24 minutes ago   https://github.com/opencpn-manuals/plugins/pull/44#issuecomment-921050799
I have named my local repos for opencpn-manuls/plugins   as OM-plugins   exactly   -- to distinguish from opencpn/plugins

**Comment by leamas** [comment]
That comment is lengthy, but i miss the first part. What's your current HEAD?

**Comment by leamas** [comment]
The canonical way to display HEAD is `git rev-parse --short HEAD`. What does this say in your box?

**Comment by leamas** [comment]
OK. I have inspected the PR in #45. It seems to live in opencpn-manuals/plugins in a branch named build. All changes in the build branch are present in current main. I have built it, and you should be able to inspect the results at https://opencpn-manuals.github.io/plugins.

No idea why you couldn't make it build, but you *must* have pushed something else.

**Comment by leamas** [comment]
Nope, sorry, it does indeed not build. No idea why. Off the see Dune.

**Comment by leamas** [comment]
It's a bug in source-state.sh...

**Comment by rgleason** [comment]
Rick@Dart MINGW64 ~/documents/github/OM-plugins (main)
$ git rev-parse --short HEAD
3bc4cee

Nice way.   Sorry, I seem to be finding some troubles, but I think something changed in the middle of my operation maybe?    -- BTW  when I am using online edit  and I am prompted to fork a plugin and I then work on it online, there isn't any requirement that I update my local opencpn-manuals/plugins  is there?    -Trying to figure out how that happened. 

But now I am not to use the "Edit Button" for opencpn-manuals/plugins!   only for distributed plugins  
So now I will be editing things locally and rebase frequently.

**Comment by rgleason** [comment]
That is a commit I made from 22 hours ago for a smaller PIM icon
I am going to get current

**Comment by rgleason** [comment]
From your comment 40 minutes ago  https://github.com/opencpn-manuals/plugins/pull/44#issuecomment-921084905

I reviewed   Dashboard  for my changes  and they aren't there
https://opencpn-manuals.github.io/plugins/opencpn-plugins/0.1/dashboard/dashboard.html
I was trying to fix the bad link and made some othere format changes.

Wouldn't they show up as a PR here?
https://github.com/OpenCPN/OpenCPN/pulls

**Comment by rgleason** [comment]
Suggest you try  Dashboard  "Edit this page"

**Comment by Rasbats** [comment]
If you "Edit this page" and cancel you are taken to the Dashboard.adoc in Github. Edit there and save. Then you would need to pull those changes to your clone and restore, update, save.

**Comment by Rasbats** [comment]
But in Github change from build branch to main. Not sure if "Edit this page" can be removed for the included plugins.

**Comment by rgleason** [comment]
These changes made it into "Main"

- Update draw-messaging.adoc  db28ea4
- Fix celestial_navigation link  d9207d9
- Fix a link   7f7ae3a
- Update draw-messaging.adoc  5e5368f   

These commits did not make it into Main  in so far as I know

- Update Draw Messaging  17bd24a
- Merge branch 'main' into build  8b0e95a
- Update dashboard.adoc to fix link  4ec7053
- fix some format   8c9c55f 

Note Alec does not want us using "Edit this page" for these opencpn-manual/plugins  pages

**Comment by Rasbats** [comment]
@rgleason : I will take a look at those failed (?) commits tomorrow.

**Comment by rgleason** [comment]
Alec, don't worry about those.  Will redo.    Just trying to learn what happened.
Should have stopped adding commits at the first fail!

Have done this now
  git remote update origin
----downloads occur
  git rebase main/orgin
  git rev-parse --short HEAD
  db56893

  ./source-state.sh update
  check-sources 

-    No manual/site.yml found in plugins/sources/aisradar_pi
-    Found that aisradar from nohal has no site.xml!
-    Why not change source to rgleason?
 
Then build docs with
antora site.yml

**Comment by rgleason** [comment]
Found internal plugin documents here  locally

C:\Users...Documents\GitHub\OM-plugins\manual\master-plugins\modules\dashboard\pages

Now can fix the link

**Comment by leamas** [comment]
Builds are up again after ca94c82.

**Comment by rgleason** [comment]
Thanks

**Comment by leamas** [comment]
> But in Github change from build branch to main. Not sure if "Edit this page" can be removed for the included plugins.

It's about repos. It's possible to remove the "Edit This Page" for the opencpn-manuals/plugins repo; perhaps we should.

OTOH: To be frank, again: If Mike or I  could handle these PRs I think everything will be fine, it's not that messy.

**Comment by leamas** [comment]
> Wouldn't they show up as a PR here?

No. The "included" (not that good term,  BTW) plugins are part of the overall opencpn-manuals/plugins repo, so PRs ends up there.

**Comment by leamas** [comment]
> Should have stopped adding commits at the first fail!

yes. And make the commits one by one, don't wait until you have a long queue. Makes rebasing simpler.

**Pull request merged**
