### PR TITLE
Draw messaging  fix plugin name

### PR DESCRIPTION
**Pull request by rgleason**

### CODE REVIEW

**Comment by rgleason** [comment]
This is failing in actions due to some unrelated problem with admiralty

error: Local content source does not exist: /home/runner/work/plugins/plugins/sources/admiralty_tide_tables_pi (url: sources/admiralty_tide_tables_pi)

**Comment by leamas** [comment]
Remove _sources/admiralty_tide_tables_pi_ and re-run _./source-state.sh restore_.

**Comment by rgleason** [comment]
Should I remove  all folders in "sources"
Should I  
```
$ git remote update origin
$ git rebase origin/main
```

**Comment by leamas** [comment]
You should

> Remove sources/admiralty_tide_tables_pi and re-run ./source-state.sh restore.

**Comment by rgleason** [comment]
Ok

**Comment by rgleason** [comment]
Did that.   Removed sources/admiralty_tide_tables_pi   and  ran ./source-state.sh restore
Admiralty Tide downloaded.
Then there were many refspec errors.

EG
Receiving objects: 100% (6/6), 52.57 KiB | 3.29 MiB/s, done.
fatal: invalid refspec 'fa4b6e4de7073fa646ac68336dade1c7cff17140?'
error: pathspec 'FETCH_HEAD' did not match any file(s) known to git
fatal: invalid refspec '296812e4b5b3b38d9c827527ed86360067af4f35?'   <--- For AISradar
fatal: invalid refspec 'ed3b8469ada185ffaa77cf9be790928b6376cdf6?'     <--- for autopilot route 

Now what?  Run it again?   do  ./source-state.sh update?

**Comment by rgleason** [comment]
Running restore again resulted in all fatal.
Running  ./source-state.sh update twice got the list clean and updated.

**Comment by rgleason** [comment]
Now still have this problem 

https://github.com/opencpn-manuals/plugins/pull/44

Should I now  ./source-state.sh save?

**Pull request merged**
