### PR TITLE
plugins review PR

### PR DESCRIPTION
**Pull request by leamas**

### CODE REVIEW

**Comment by Rasbats** [comment]
Empty commit is not building this morning. Fails at radar_pi. Missing .git in sources.state. Trying again.

**Comment by Rasbats** [comment]
Build failed again. opencpn-manuals does not have a radar_pi forked repo.

**Comment by leamas** [comment]
But now... probably my bad, these changes of upstream are potentially de-stabilizing

**Comment by leamas** [comment]
BTW: This PR and branch is just an experiment. I might remove it any time...

**Comment by Rasbats** [comment]
Kees has accepted your PR for radar_pi. I am going to update sources.state and site.yml and test again.

**Comment by leamas** [comment]
Already done.

**Comment by leamas** [comment]
You need to rebase to pick up recent changes.

**Comment by leamas** [comment]
hm... what are you trying to achieve by merging this?

**Comment by Rasbats** [comment]
>BTW: This PR and branch is just an experiment. I might remove it any time...

Sorry ... what was the reason for this PR if not to add a review branch?

**Comment by leamas** [comment]
It was an experiment. Before it was merged it was possible to annotate the PR, if we should do a  review. That opportunity is lost when the PR is merged. 

No big deal, re-creating the PR is a matter of seconds.

The bigger issue is if we should try to organize a review of at least some parts. Dunno. Better discussed in https://github.com/opencpn-manuals/main/discussions/16

**Pull request merged**
